import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export type PdfDocInput = {
  title: string;
  number: string;
  companyName: string;
  partnerLabel?: string;
  partnerName?: string;
  dateLabel?: string;
  dateValue?: string;
  notes?: string;
  lines: Array<{
    description: string;
    qty: string;
    price: string;
    total: string;
  }>;
  totals?: Array<{ label: string; value: string }>;
};

export async function buildSimplePdf(input: PdfDocInput): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const page = doc.addPage([595, 842]);
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const { width, height } = page.getSize();
  let y = height - 50;

  const draw = (
    text: string,
    x: number,
    size = 10,
    useBold = false,
  ) => {
    page.drawText(text.slice(0, 110), {
      x,
      y,
      size,
      font: useBold ? bold : font,
      color: rgb(0.1, 0.1, 0.1),
    });
  };

  draw(input.companyName, 50, 14, true);
  y -= 22;
  draw(input.title, 50, 16, true);
  y -= 18;
  draw(`No: ${input.number}`, 50, 11, true);
  y -= 16;
  if (input.partnerName) {
    draw(`${input.partnerLabel || "Partner"}: ${input.partnerName}`, 50);
    y -= 14;
  }
  if (input.dateValue) {
    draw(`${input.dateLabel || "Tanggal"}: ${input.dateValue}`, 50);
    y -= 14;
  }
  y -= 10;
  page.drawLine({
    start: { x: 50, y },
    end: { x: width - 50, y },
    thickness: 1,
    color: rgb(0.7, 0.7, 0.7),
  });
  y -= 20;

  draw("Item", 50, 10, true);
  draw("Qty", 300, 10, true);
  draw("Harga", 360, 10, true);
  draw("Total", 460, 10, true);
  y -= 14;

  for (const line of input.lines) {
    if (y < 80) break;
    draw(line.description || "-", 50);
    draw(line.qty, 300);
    draw(line.price, 360);
    draw(line.total, 460);
    y -= 14;
  }

  y -= 10;
  page.drawLine({
    start: { x: 50, y },
    end: { x: width - 50, y },
    thickness: 1,
    color: rgb(0.7, 0.7, 0.7),
  });
  y -= 18;

  for (const t of input.totals || []) {
    draw(`${t.label}: ${t.value}`, 360, 11, true);
    y -= 14;
  }

  if (input.notes) {
    y -= 10;
    draw(`Catatan: ${input.notes}`, 50, 9);
  }

  y = 40;
  draw("Generated by Arunika ERP", 50, 8);

  return doc.save();
}
