export const PERMISSIONS = [
  // platform
  "company:view",
  "company:update",
  "branch:view",
  "branch:create",
  "branch:update",
  "branch:delete",
  "user:view",
  "user:invite",
  "user:update",
  "user:disable",
  "role:view",
  "role:manage",
  "settings:manage",
  "audit:view",
  "report:view",
  "report:export",
  // master
  "product:view",
  "product:create",
  "product:update",
  "product:archive",
  "customer:view",
  "customer:create",
  "customer:update",
  "supplier:view",
  "supplier:create",
  "supplier:update",
  "warehouse:view",
  "warehouse:create",
  "warehouse:update",
  // inventory
  "stock:view",
  "stock:adjust",
  "stock:transfer",
  "stock:opname",
  // procurement core
  "purchase_order:view",
  "purchase_order:create",
  "purchase_order:update",
  "purchase_order:submit",
  "purchase_order:approve",
  "purchase_order:cancel",
  "goods_receipt:view",
  "goods_receipt:create",
  "goods_receipt:post",
  "supplier_bill:view",
  "supplier_bill:create",
  "supplier_payment:view",
  "supplier_payment:create",
  "supplier_payment:void",
  // sales
  "sales_order:view",
  "sales_order:create",
  "sales_order:update",
  "sales_order:submit",
  "sales_order:approve",
  "sales_order:cancel",
  "delivery_order:view",
  "delivery_order:create",
  "delivery_order:post",
  "invoice:view",
  "invoice:create",
  "invoice:issue",
  "invoice:void",
  "payment:view",
  "payment:create",
  "payment:void",
  // accounting
  "account:view",
  "account:manage",
  "journal:view",
  "journal:create",
  "journal:post",
  "journal:reverse",
  "period:view",
  "period:close",
  "period:reopen",
  "bank_account:view",
  "bank_account:manage",
  "bank_reconciliation:perform",
  "budget:view",
  "budget:manage",
  "fixed_asset:view",
  "fixed_asset:manage",
  "financial_statement:view",
  // tax
  "tax:view",
  "tax:configure",
  "tax_document:create",
  "tax_document:approve",
  "tax_document:correct",
  "tax_period:close",
  "tax_export:generate",
  // advanced procurement
  "purchase_request:view",
  "purchase_request:create",
  "purchase_request:approve",
  "rfq:view",
  "rfq:create",
  "rfq:award",
  "contract:view",
  "contract:manage",
  "vendor_evaluation:view",
  "vendor_evaluation:manage",
  "three_way_match:review",
  // manufacturing
  "bom:view",
  "bom:manage",
  "routing:view",
  "routing:manage",
  "work_center:view",
  "work_center:manage",
  "mrp:view",
  "mrp:run",
  "production_order:view",
  "production_order:create",
  "production_order:release",
  "production_order:report",
  "production_order:close",
  "quality_inspection:view",
  "quality_inspection:record",
  // hr
  "employee:view",
  "employee:manage",
  "employee_sensitive:view",
  "attendance:view",
  "attendance:manage",
  "leave:view",
  "leave:approve",
  // payroll
  "payroll:view",
  "payroll:prepare",
  "payroll:approve",
  "payroll:post",
  "payslip:view_all",
  // returns
  "return:view",
  "return:create",
  "return:approve",
  "return:post",
  "claim:view",
  "claim:manage",
  "credit_note:create",
  "debit_note:create",
  // project
  "project:view",
  "project:create",
  "project:manage",
  "project_budget:view",
  "project_budget:manage",
  "timesheet:view",
  "timesheet:approve",
  "project_billing:create",
  "project_profitability:view",
] as const;

export type PermissionCode = (typeof PERMISSIONS)[number];

export const PERMISSION_META: Record<
  PermissionCode,
  { name: string; module: string }
> = {
  "company:view": { name: "Lihat perusahaan", module: "admin" },
  "company:update": { name: "Ubah perusahaan", module: "admin" },
  "branch:view": { name: "Lihat cabang", module: "admin" },
  "branch:create": { name: "Buat cabang", module: "admin" },
  "branch:update": { name: "Ubah cabang", module: "admin" },
  "branch:delete": { name: "Hapus cabang", module: "admin" },
  "user:view": { name: "Lihat pengguna", module: "admin" },
  "user:invite": { name: "Undang pengguna", module: "admin" },
  "user:update": { name: "Ubah pengguna", module: "admin" },
  "user:disable": { name: "Nonaktifkan pengguna", module: "admin" },
  "role:view": { name: "Lihat role", module: "admin" },
  "role:manage": { name: "Kelola role", module: "admin" },
  "settings:manage": { name: "Kelola pengaturan", module: "admin" },
  "audit:view": { name: "Lihat audit log", module: "admin" },
  "report:view": { name: "Lihat laporan", module: "report" },
  "report:export": { name: "Ekspor laporan", module: "report" },
  "product:view": { name: "Lihat produk", module: "master" },
  "product:create": { name: "Buat produk", module: "master" },
  "product:update": { name: "Ubah produk", module: "master" },
  "product:archive": { name: "Arsip produk", module: "master" },
  "customer:view": { name: "Lihat pelanggan", module: "master" },
  "customer:create": { name: "Buat pelanggan", module: "master" },
  "customer:update": { name: "Ubah pelanggan", module: "master" },
  "supplier:view": { name: "Lihat pemasok", module: "master" },
  "supplier:create": { name: "Buat pemasok", module: "master" },
  "supplier:update": { name: "Ubah pemasok", module: "master" },
  "warehouse:view": { name: "Lihat gudang", module: "master" },
  "warehouse:create": { name: "Buat gudang", module: "master" },
  "warehouse:update": { name: "Ubah gudang", module: "master" },
  "stock:view": { name: "Lihat stok", module: "inventory" },
  "stock:adjust": { name: "Penyesuaian stok", module: "inventory" },
  "stock:transfer": { name: "Transfer stok", module: "inventory" },
  "stock:opname": { name: "Stock opname", module: "inventory" },
  "purchase_order:view": { name: "Lihat PO", module: "procurement" },
  "purchase_order:create": { name: "Buat PO", module: "procurement" },
  "purchase_order:update": { name: "Ubah PO", module: "procurement" },
  "purchase_order:submit": { name: "Ajukan PO", module: "procurement" },
  "purchase_order:approve": { name: "Setujui PO", module: "procurement" },
  "purchase_order:cancel": { name: "Batalkan PO", module: "procurement" },
  "goods_receipt:view": { name: "Lihat penerimaan", module: "procurement" },
  "goods_receipt:create": { name: "Buat penerimaan", module: "procurement" },
  "goods_receipt:post": { name: "Posting penerimaan", module: "procurement" },
  "supplier_bill:view": { name: "Lihat tagihan pemasok", module: "procurement" },
  "supplier_bill:create": { name: "Buat tagihan pemasok", module: "procurement" },
  "supplier_payment:view": { name: "Lihat bayar pemasok", module: "procurement" },
  "supplier_payment:create": { name: "Buat bayar pemasok", module: "procurement" },
  "supplier_payment:void": { name: "Void bayar pemasok", module: "procurement" },
  "sales_order:view": { name: "Lihat SO", module: "sales" },
  "sales_order:create": { name: "Buat SO", module: "sales" },
  "sales_order:update": { name: "Ubah SO", module: "sales" },
  "sales_order:submit": { name: "Ajukan SO", module: "sales" },
  "sales_order:approve": { name: "Setujui SO", module: "sales" },
  "sales_order:cancel": { name: "Batalkan SO", module: "sales" },
  "delivery_order:view": { name: "Lihat pengiriman", module: "sales" },
  "delivery_order:create": { name: "Buat pengiriman", module: "sales" },
  "delivery_order:post": { name: "Posting pengiriman", module: "sales" },
  "invoice:view": { name: "Lihat invoice", module: "sales" },
  "invoice:create": { name: "Buat invoice", module: "sales" },
  "invoice:issue": { name: "Terbitkan invoice", module: "sales" },
  "invoice:void": { name: "Void invoice", module: "sales" },
  "payment:view": { name: "Lihat pembayaran", module: "sales" },
  "payment:create": { name: "Buat pembayaran", module: "sales" },
  "payment:void": { name: "Void pembayaran", module: "sales" },
  "account:view": { name: "Lihat COA", module: "accounting" },
  "account:manage": { name: "Kelola COA", module: "accounting" },
  "journal:view": { name: "Lihat jurnal", module: "accounting" },
  "journal:create": { name: "Buat jurnal", module: "accounting" },
  "journal:post": { name: "Posting jurnal", module: "accounting" },
  "journal:reverse": { name: "Reverse jurnal", module: "accounting" },
  "period:view": { name: "Lihat periode", module: "accounting" },
  "period:close": { name: "Tutup periode", module: "accounting" },
  "period:reopen": { name: "Buka periode", module: "accounting" },
  "bank_account:view": { name: "Lihat rekening", module: "treasury" },
  "bank_account:manage": { name: "Kelola rekening", module: "treasury" },
  "bank_reconciliation:perform": { name: "Rekonsiliasi bank", module: "treasury" },
  "budget:view": { name: "Lihat budget", module: "treasury" },
  "budget:manage": { name: "Kelola budget", module: "treasury" },
  "fixed_asset:view": { name: "Lihat aset", module: "treasury" },
  "fixed_asset:manage": { name: "Kelola aset", module: "treasury" },
  "financial_statement:view": { name: "Lihat laporan keuangan", module: "accounting" },
  "tax:view": { name: "Lihat pajak", module: "tax" },
  "tax:configure": { name: "Konfigurasi pajak", module: "tax" },
  "tax_document:create": { name: "Buat dokumen pajak", module: "tax" },
  "tax_document:approve": { name: "Setujui dokumen pajak", module: "tax" },
  "tax_document:correct": { name: "Koreksi dokumen pajak", module: "tax" },
  "tax_period:close": { name: "Tutup periode pajak", module: "tax" },
  "tax_export:generate": { name: "Ekspor data pajak", module: "tax" },
  "purchase_request:view": { name: "Lihat PR", module: "procurement" },
  "purchase_request:create": { name: "Buat PR", module: "procurement" },
  "purchase_request:approve": { name: "Setujui PR", module: "procurement" },
  "rfq:view": { name: "Lihat RFQ", module: "procurement" },
  "rfq:create": { name: "Buat RFQ", module: "procurement" },
  "rfq:award": { name: "Award RFQ", module: "procurement" },
  "contract:view": { name: "Lihat kontrak", module: "procurement" },
  "contract:manage": { name: "Kelola kontrak", module: "procurement" },
  "vendor_evaluation:view": { name: "Lihat evaluasi vendor", module: "procurement" },
  "vendor_evaluation:manage": { name: "Kelola evaluasi vendor", module: "procurement" },
  "three_way_match:review": { name: "Review three-way match", module: "procurement" },
  "bom:view": { name: "Lihat BOM", module: "manufacturing" },
  "bom:manage": { name: "Kelola BOM", module: "manufacturing" },
  "routing:view": { name: "Lihat routing", module: "manufacturing" },
  "routing:manage": { name: "Kelola routing", module: "manufacturing" },
  "work_center:view": { name: "Lihat work center", module: "manufacturing" },
  "work_center:manage": { name: "Kelola work center", module: "manufacturing" },
  "mrp:view": { name: "Lihat MRP", module: "manufacturing" },
  "mrp:run": { name: "Jalankan MRP", module: "manufacturing" },
  "production_order:view": { name: "Lihat production order", module: "manufacturing" },
  "production_order:create": { name: "Buat production order", module: "manufacturing" },
  "production_order:release": { name: "Release production order", module: "manufacturing" },
  "production_order:report": { name: "Lapor produksi", module: "manufacturing" },
  "production_order:close": { name: "Tutup production order", module: "manufacturing" },
  "quality_inspection:view": { name: "Lihat QC", module: "manufacturing" },
  "quality_inspection:record": { name: "Catat QC", module: "manufacturing" },
  "employee:view": { name: "Lihat karyawan", module: "hr" },
  "employee:manage": { name: "Kelola karyawan", module: "hr" },
  "employee_sensitive:view": { name: "Lihat data sensitif karyawan", module: "hr" },
  "attendance:view": { name: "Lihat absensi", module: "hr" },
  "attendance:manage": { name: "Kelola absensi", module: "hr" },
  "leave:view": { name: "Lihat cuti", module: "hr" },
  "leave:approve": { name: "Setujui cuti", module: "hr" },
  "payroll:view": { name: "Lihat payroll", module: "payroll" },
  "payroll:prepare": { name: "Siapkan payroll", module: "payroll" },
  "payroll:approve": { name: "Setujui payroll", module: "payroll" },
  "payroll:post": { name: "Posting payroll", module: "payroll" },
  "payslip:view_all": { name: "Lihat semua payslip", module: "payroll" },
  "return:view": { name: "Lihat return", module: "returns" },
  "return:create": { name: "Buat return", module: "returns" },
  "return:approve": { name: "Setujui return", module: "returns" },
  "return:post": { name: "Posting return", module: "returns" },
  "claim:view": { name: "Lihat claim", module: "returns" },
  "claim:manage": { name: "Kelola claim", module: "returns" },
  "credit_note:create": { name: "Buat credit note", module: "returns" },
  "debit_note:create": { name: "Buat debit note", module: "returns" },
  "project:view": { name: "Lihat project", module: "project" },
  "project:create": { name: "Buat project", module: "project" },
  "project:manage": { name: "Kelola project", module: "project" },
  "project_budget:view": { name: "Lihat budget project", module: "project" },
  "project_budget:manage": { name: "Kelola budget project", module: "project" },
  "timesheet:view": { name: "Lihat timesheet", module: "project" },
  "timesheet:approve": { name: "Setujui timesheet", module: "project" },
  "project_billing:create": { name: "Buat billing project", module: "project" },
  "project_profitability:view": { name: "Lihat profitabilitas project", module: "project" },
};

export const ROLE_PERMISSIONS: Record<string, PermissionCode[] | "*"> = {
  OWNER: "*",
  ADMIN: "*",
  FINANCE_MANAGER: [
    "company:view",
    "branch:view",
    "report:view",
    "report:export",
    "audit:view",
    "supplier_bill:view",
    "supplier_bill:create",
    "supplier_payment:view",
    "supplier_payment:create",
    "supplier_payment:void",
    "invoice:view",
    "invoice:create",
    "invoice:issue",
    "invoice:void",
    "payment:view",
    "payment:create",
    "payment:void",
    "account:view",
    "account:manage",
    "journal:view",
    "journal:create",
    "journal:post",
    "journal:reverse",
    "period:view",
    "period:close",
    "period:reopen",
    "bank_account:view",
    "bank_account:manage",
    "bank_reconciliation:perform",
    "budget:view",
    "budget:manage",
    "fixed_asset:view",
    "fixed_asset:manage",
    "financial_statement:view",
    "tax:view",
    "tax:configure",
    "tax_document:create",
    "tax_document:approve",
    "tax_document:correct",
    "tax_period:close",
    "tax_export:generate",
    "three_way_match:review",
    "stock:view",
    "product:view",
    "customer:view",
    "supplier:view",
  ],
  ACCOUNTANT: [
    "company:view",
    "report:view",
    "report:export",
    "supplier_bill:view",
    "supplier_bill:create",
    "supplier_payment:view",
    "invoice:view",
    "invoice:create",
    "invoice:issue",
    "payment:view",
    "payment:create",
    "account:view",
    "journal:view",
    "journal:create",
    "journal:post",
    "period:view",
    "bank_account:view",
    "bank_reconciliation:perform",
    "budget:view",
    "fixed_asset:view",
    "financial_statement:view",
    "tax:view",
    "tax_document:create",
    "stock:view",
    "product:view",
    "customer:view",
    "supplier:view",
  ],
  TAX_OFFICER: [
    "company:view",
    "tax:view",
    "tax:configure",
    "tax_document:create",
    "tax_document:approve",
    "tax_document:correct",
    "tax_period:close",
    "tax_export:generate",
    "invoice:view",
    "supplier_bill:view",
    "report:view",
    "report:export",
  ],
  PROCUREMENT_MANAGER: [
    "company:view",
    "branch:view",
    "warehouse:view",
    "product:view",
    "supplier:view",
    "supplier:create",
    "supplier:update",
    "stock:view",
    "purchase_order:view",
    "purchase_order:create",
    "purchase_order:update",
    "purchase_order:submit",
    "purchase_order:approve",
    "purchase_order:cancel",
    "goods_receipt:view",
    "purchase_request:view",
    "purchase_request:create",
    "purchase_request:approve",
    "rfq:view",
    "rfq:create",
    "rfq:award",
    "contract:view",
    "contract:manage",
    "vendor_evaluation:view",
    "vendor_evaluation:manage",
    "three_way_match:review",
    "report:view",
  ],
  BUYER: [
    "company:view",
    "product:view",
    "supplier:view",
    "supplier:create",
    "supplier:update",
    "stock:view",
    "purchase_order:view",
    "purchase_order:create",
    "purchase_order:update",
    "purchase_order:submit",
    "goods_receipt:view",
    "purchase_request:view",
    "purchase_request:create",
    "rfq:view",
    "rfq:create",
    "contract:view",
  ],
  SALES_MANAGER: [
    "company:view",
    "product:view",
    "customer:view",
    "customer:create",
    "customer:update",
    "stock:view",
    "sales_order:view",
    "sales_order:create",
    "sales_order:update",
    "sales_order:submit",
    "sales_order:approve",
    "sales_order:cancel",
    "delivery_order:view",
    "invoice:view",
    "invoice:create",
    "invoice:issue",
    "payment:view",
    "report:view",
  ],
  SALES: [
    "company:view",
    "product:view",
    "customer:view",
    "customer:create",
    "customer:update",
    "stock:view",
    "sales_order:view",
    "sales_order:create",
    "sales_order:update",
    "sales_order:submit",
    "delivery_order:view",
    "invoice:view",
    "payment:view",
  ],
  WAREHOUSE_MANAGER: [
    "company:view",
    "product:view",
    "warehouse:view",
    "warehouse:create",
    "warehouse:update",
    "stock:view",
    "stock:adjust",
    "stock:transfer",
    "stock:opname",
    "goods_receipt:view",
    "goods_receipt:create",
    "goods_receipt:post",
    "delivery_order:view",
    "delivery_order:create",
    "delivery_order:post",
  ],
  WAREHOUSE: [
    "company:view",
    "product:view",
    "warehouse:view",
    "stock:view",
    "stock:transfer",
    "goods_receipt:view",
    "goods_receipt:create",
    "goods_receipt:post",
    "delivery_order:view",
    "delivery_order:create",
    "delivery_order:post",
  ],
  AUDITOR: [
    "company:view",
    "branch:view",
    "warehouse:view",
    "product:view",
    "customer:view",
    "supplier:view",
    "stock:view",
    "purchase_order:view",
    "goods_receipt:view",
    "supplier_bill:view",
    "supplier_payment:view",
    "sales_order:view",
    "delivery_order:view",
    "invoice:view",
    "payment:view",
    "account:view",
    "journal:view",
    "period:view",
    "financial_statement:view",
    "tax:view",
    "audit:view",
    "report:view",
    "report:export",
    "bom:view",
    "routing:view",
    "work_center:view",
    "mrp:view",
    "production_order:view",
    "employee:view",
    "payroll:view",
    "return:view",
    "claim:view",
    "project:view",
    "project_profitability:view",
  ],
  VIEWER: [
    "company:view",
    "product:view",
    "customer:view",
    "supplier:view",
    "stock:view",
    "purchase_order:view",
    "sales_order:view",
    "invoice:view",
    "report:view",
    "bom:view",
    "production_order:view",
    "project:view",
  ],
  PRODUCTION_PLANNER: [
    "company:view",
    "product:view",
    "stock:view",
    "warehouse:view",
    "bom:view",
    "bom:manage",
    "routing:view",
    "routing:manage",
    "work_center:view",
    "work_center:manage",
    "mrp:view",
    "mrp:run",
    "production_order:view",
    "production_order:create",
    "production_order:release",
    "production_order:report",
    "report:view",
  ],
  PRODUCTION_SUPERVISOR: [
    "company:view",
    "product:view",
    "stock:view",
    "warehouse:view",
    "bom:view",
    "routing:view",
    "work_center:view",
    "production_order:view",
    "production_order:report",
    "production_order:close",
    "quality_inspection:view",
    "quality_inspection:record",
  ],
  HR_MANAGER: [
    "company:view",
    "employee:view",
    "employee:manage",
    "employee_sensitive:view",
    "attendance:view",
    "attendance:manage",
    "leave:view",
    "leave:approve",
    "payroll:view",
    "report:view",
  ],
  HR_ADMIN: [
    "company:view",
    "employee:view",
    "employee:manage",
    "attendance:view",
    "attendance:manage",
    "leave:view",
    "leave:approve",
  ],
  PAYROLL_ADMIN: [
    "company:view",
    "employee:view",
    "employee_sensitive:view",
    "attendance:view",
    "payroll:view",
    "payroll:prepare",
    "payroll:approve",
    "payroll:post",
    "payslip:view_all",
    "journal:view",
    "account:view",
  ],
  PROJECT_MANAGER: [
    "company:view",
    "project:view",
    "project:create",
    "project:manage",
    "project_budget:view",
    "project_budget:manage",
    "timesheet:view",
    "timesheet:approve",
    "project_billing:create",
    "project_profitability:view",
    "product:view",
    "customer:view",
    "report:view",
  ],
  PROJECT_MEMBER: [
    "company:view",
    "project:view",
    "timesheet:view",
    "project_budget:view",
  ],
};

export const SYSTEM_ROLES = [
  { code: "OWNER", name: "Owner" },
  { code: "ADMIN", name: "Admin" },
  { code: "FINANCE_MANAGER", name: "Finance Manager" },
  { code: "ACCOUNTANT", name: "Accountant" },
  { code: "TAX_OFFICER", name: "Tax Officer" },
  { code: "PROCUREMENT_MANAGER", name: "Procurement Manager" },
  { code: "BUYER", name: "Buyer" },
  { code: "SALES_MANAGER", name: "Sales Manager" },
  { code: "SALES", name: "Sales" },
  { code: "WAREHOUSE_MANAGER", name: "Warehouse Manager" },
  { code: "WAREHOUSE", name: "Warehouse" },
  { code: "PRODUCTION_PLANNER", name: "Production Planner" },
  { code: "PRODUCTION_SUPERVISOR", name: "Production Supervisor" },
  { code: "HR_MANAGER", name: "HR Manager" },
  { code: "HR_ADMIN", name: "HR Administrator" },
  { code: "PAYROLL_ADMIN", name: "Payroll Administrator" },
  { code: "PROJECT_MANAGER", name: "Project Manager" },
  { code: "PROJECT_MEMBER", name: "Project Member" },
  { code: "AUDITOR", name: "Auditor" },
  { code: "VIEWER", name: "Viewer" },
] as const;

export function hasPermission(
  granted: ReadonlySet<string> | string[] | "*",
  required: PermissionCode | PermissionCode[],
): boolean {
  if (granted === "*") return true;
  const set = granted instanceof Set ? granted : new Set(granted);
  const list = Array.isArray(required) ? required : [required];
  return list.every((p) => set.has(p));
}
